# Path to your oh-my-zsh installation.
  export ZSH=/home/yurtle/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="simple"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

  export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

sol_base03="002b36"
sol_base02="073642"
sol_base01="586e75"
sol_base00="657b83"
sol_base0="839496"
sol_base1="93a1a1"
sol_base2="eee8d5"
sol_base3="fdf6e3"
sol_yellow="b58900"
sol_orange="cb4b16"
sol_red="dc322f"
sol_magenta="d33682"
sol_violet="6c71c4"
sol_blue="268bd2"
sol_cyan="2aa198"
sol_green="859900"

mood="dark"

if [ "$TERM" = "linux" ]; then
	if [ "$mood" = "dark" ]; then
		echo -en "\e]P0$sol_base03"	#black
		echo -en "\e]P7$sol_base2"	#white
		echo -en "\e]P8$sol_base02"	#brblack / gray
		echo -en "\e]PF$sol_base3"	#brwhite
	fi
	if [ "$mood" = "light" ]; then
		echo -en "\e]P0$sol_base3"	#black
		echo -en "\e]P7$sol_base02"	#white
		echo -en "\e]P8$sol_base2"	#brblack / gray
		echo -en "\e]PF$sol_base03"	#brwhite

	fi
	echo -en "\e]P1$sol_red"	#red
	echo -en "\e]P2$sol_green"	#green
	echo -en "\e]P3$sol_yellow"	#yellow
	echo -en "\e]P4$sol_blue"	#blue
	echo -en "\e]P5$sol_magenta"	#magenta
	echo -en "\e]P6$sol_cyan"	#cyan
	echo -en "\e]P9$sol_orange"	#brred
	echo -en "\e]PA$sol_base01"	#brgreen
	echo -en "\e]PB$sol_base00"	#bryellow
	echo -en "\e]PC$sol_base0"	#brblue
	echo -en "\e]PD$sol_violet"	#brmagenta
	echo -en "\e]PE$sol_base1"	#brcyan


fi

alias ls="ls --color"
alias bri="cat /sys/class/backlight/acpi_video0/brightness"
alias chbri="sudo tee /sys/class/backlight/acpi_video0/brightness <<<"
